files_config:
  area: warm.area
  check: warm.chk
  conductivity: warm.cond
  error: warm.err
  files: fehmn.files
  final_conditions: warm.fin
  grid: warm.fehm
  history: warm.hist
  input: warm.dat
  material_zone: warm_material.zone
  output: warm.out
  outside_zone: warm_outside.zone
  permeability: warm.perm
  pore_pressure: warm.ppor
  rock_properties: warm.rock
  run_root: warm
  storage: warm.stor
  water_properties: warm.wpi
  flow: warm.flow
  heat_flux: warm.hflx

heat_flux_config:
  boundary_configs:
  - boundary_model:
      kind: crustal_age
      params:
        crustal_age_sign: 1
        crustal_age_dimension: x
        spread_rate_mm_per_year: 28.57
        coefficient_MW: 0.367E-6
        boundary_distance_to_ridge_m: 60000
    outside_zones: ['bottom']

flow_config:
  boundary_configs:
  - boundary_model:
      kind: open_flow
      params:
        aiped_to_volume_ratio: 1.0e-08
        input_fluid_temp_degC: 2
    outside_zones: [top]

rock_properties_config:
  compressibility_configs:
  - property_model:
      kind: overburden
      params:
        a: 0.09
        grav: 9.81
        min_overburden: 25
        rhow: 1000
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 6.0E-10
    zones: [2, 3]
  conductivity_configs:
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 2.05
        water_conductivity: 0.62
    zones: [1]
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 2.05
        water_conductivity: 0.62
    zones: [2, 3]
  grain_density_configs:
  - property_model:
      kind: constant
      params:
        constant: 2650
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 2700
    zones: [2, 3]
  permeability_configs:
  - property_model:
      kind: constant
      params:
        constant: 1.0E-15
    zones: [1, 2, 3]
  porosity_configs:
  - property_model:
      kind: depth_power_law_with_maximum
      params:
        porosity_a: 0.84
        porosity_b: -0.125
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 0.1
    zones: [2]
  - property_model:
      kind: constant
      params:
        constant: 0.05
    zones: [3]
  specific_heat_configs:
  - property_model:
      kind: constant
      params:
        constant: 800
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 800
    zones: [2, 3]
  zone_assignment_order: [1, 2, 3]
